services:
  pinger:
    build:
      context: ./Pinger
    depends_on:
      - dockmon
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      backend:
    cap_add:
      - NET_RAW
    
  postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    
  dockmon:
    build:
      context: ./DockMon
    container_name: dockmon
    environment:
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      backend:
    ports:
      - "127.0.0.1:8080:8080"
    
networks:
  backend:
    driver: bridge